name: Auto PR dev → main

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

env:
  NO_COLOR: 1  # Disable colors in CI for consistent output

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Open or update PR from dev to main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          # Check if there are any changes between dev and main
          if git rev-parse --verify main >/dev/null 2>&1 && git merge-base --is-ancestor dev main; then
            echo "dev branch is not ahead of main. No PR needed."
            exit 0
          fi

          # Check if an open PR from dev->main already exists
          EXISTING_PR=$(gh pr list --base main --head dev --state open --json number --jq '.[0].number // empty')
          if [ -n "$EXISTING_PR" ]; then
            echo "PR from dev to main already exists (#$EXISTING_PR). Skipping creation."
            exit 0
          fi

          # Create a PR. Reviewers can enable auto-merge in the UI if desired.
          echo "Creating PR from dev to main..."
          PR_URL=$(gh pr create \
            --base main \
            --head dev \
            --title "Auto PR: dev → main" \
            --body "This pull request was automatically created when commits were pushed to \`dev\`. Please review, wait for CI to pass, and merge when ready.")

          if [ $? -eq 0 ]; then
            echo "Successfully created PR: $PR_URL"
          else
            echo "Failed to create PR"
            exit 1
          fi
