name: Auto PR dev → main

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        uses: cli/cli-action@v2
        with:
          version: latest

      - name: Open or update PR from dev to main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          # If an open PR from dev->main exists, do nothing.
          if gh pr list --base main --head dev --state open --json number --jq '.[0].number' >/dev/null 2>&1; then
            echo "PR from dev to main already exists. Skipping creation."
            exit 0
          fi

          # Create a PR. Reviewers can enable auto-merge in the UI if desired.
          gh pr create \
            --base main \
            --head dev \
            --title "Auto PR: dev → main" \
            --body "This pull request was automatically created when commits were pushed to \`dev\`. Please review, wait for CI to pass, and merge when ready."
